### PR TITLE
Made links from metadata layer use license data source if present.

### PR DESCRIPTION
**Pull request by aslagle**
This connects to https://github.com/NYPL-Simplified/content_server/issues/59

### CODE REVIEW

**Comment by aslagle** [comment]
Not sure if I should change the data_source passed to mirror_link and make_thumbnail too.

**Comment by leonardr** [comment]
Nice. :nail_care:

I do think you should change the data_source passed to mirror_link and make_thumbnail. Once you do that I'll take another look!

Hopefully this will just go away once we bring in the presentation-edition code.

**Comment by aslagle** [comment]
@leonardr changed them

**Comment by leonardr** [comment]
:+1:

**Pull request merged**
